### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by bigcodersa** [byebyebruce/chat2data#3]
hey there first of all i appreciate your work this is a wonderful job . however when i try to run this project after connecting mysql db ig et this error error:API returned unexpected status code: 404: Invalid URL (POST /v1/v1/chat/completions) .. i have created an env file OPENAI_API_KEY=xxxx
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=davinci
 and changed the model to davini and still get the same issue
again thank you deeply for your work its verry much **appreciated**

**Comment by byebyebruce** [comment]
Just feel free.
Try set OPENAI_BASE_URL to empty or set OPENAI_BASE_URL=https://api.openai.com, without `/v1`

**Comment by byebyebruce** [comment]
Sorry bro, now the new lib(langchain-go) needs the suffix "/v1".
like this "OPENAI_BASE_URL=https://api.openai.com/v1"
